server:
  port: 8080
spring:


  application:
    name: stock
  datasource:
    password: password
    url: jdbc:mysql://mysql1:3306/stockDB
    username: aymen
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
  kafka:
    acks: -1
    bootstrap-servers: kafka:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: kafka:9092
      group-id: com.PFE
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: com.PFE


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true
#org.springframework.kafka.support.serializer.JsonSerializer
#org.apache.kafka.common.serialization.StringDeserializer
keycloak:

  realm: PFE
  domain: keycloak:8080
  adminClientId: admin-cli
  #adminClientSecret: dUQPvo7bfrcVpRd3b3QHt1u0YH7szUdl
  adminClientSecret: joKgYKLaCtyZIa6TTrDUgHmUDhquN0g2
  client: pfeclient
  use-resource-role-mappings: false
  urls:
    auth: http://${keycloak.domain}

jwt:
  auth:
    converter:
      resource-id: pfeclient