# Required metadata
sonar.projectKey=PFE
sonar.projectName=PFE
sonar.projectVersion=1.0

# Path to sources
sonar.sources=src/main/java

# Encoding of sources files
sonar.sourceEncoding=UTF-8

# SonarQube server connection details
sonar.host.url=http://localhost:9000

# Token for authentication
sonar.login=sqp_2878ed5cde62d01e33d4bfa5a6beb342e557bbbc
